language: python
cache: pip
python:
  - 2.7
env:
  - DJANGO_SETTINGS_MODULE=test_settings
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install --upgrade pip  # pip-tools requires pip >= 6.1
install:
  - pip install setuptools==32.3.1  # need newer version than Travis default
  - make install
script:
  - make test-all
  - gulp test
after_success:
  - coverage xml
  - bash <(curl -s https://codecov.io/bash) -cF python -f coverage.xml
  - bash <(curl -s https://codecov.io/bash) -cF javascript -f build/coverage-js/coverage.xml
