language: python
cache: pip
python:
- 2.7
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- pip install --upgrade pip setuptools wheel
install:
- pip install tox edx-i18n-tools
- npm install
before_script:
- npm install -g gulp-cli
script:
- make validate_translations
- make test-all
- make test-js
after_success:
- coverage xml
- bash <(curl -s https://codecov.io/bash) -cF python -f coverage.xml
- bash <(curl -s https://codecov.io/bash) -cF javascript -f build/coverage-js/coverage.xml
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: Xx0ya0JKOzPEX5fL389UQxiSnu46D/tVWwdgKXGT+g9GceQsxUWyshqC8uPF1KgKQfMynmC4C/XQOktfQj4LEv2EQPfnYP7Aog+swxS23jHevQYC7H0mlc5pyzTqfGbb5nr1gVtq2pjfsvC2RSgrZGigpCympyD1qKb6HBb3xcCpaUpLBMJFO+uUCIKYe6zJ0zxykW1Z66qE7igNyfvDqMbB/Sn6VO9PBrQOnTNnl4JyLer6gN+nztJTvpgwcKT7jUjtJtBDoTqj9ia/jJLGhAYNppCdLwmjNU1aN+e6X7J0HXBizOgqL7skWYAR1ygXwv027ZC3LJjiC6Ovww0rRzJdWe/OMJu5RzTYvXjgyBdjMdk3lYw5LaNoRuLfWkntV8ORYULsjl/g1RUJrXQ5u1KxeVPM9Fwb5toH1OmAMbuTpAmbYK8itWdU0TGiDsgLQABeNeW57DQIqE04YVG+kK1zg3OV7W6CgEVKXWciOugWJSdTtyoI5RBOuW1altKapee2/xwd49X5F5eac1AKsRc3U5DNxc0DCLR3NRmrHVBOD+yfI0F42MwngK9tbevDyZ9t1tf04ysu6hvzwES5goVp+85hHIyf+NIiKQpQQbKYWwIGcQuGlo7vHyOs9LJ5qHXQSzFZu8+l9qn3cCEd/cY7geh15yKOSVzv0J7yb84=
